/*
 * Generated by XDoclet - Do not edit!
 */
package com.projst.ticket.service;

/**
 * Local interface for TicketService.
 * @generated 
 * @wtp generated
 */
public interface TicketServiceLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Method used to ensure session bean is available by providing an echo message <!-- begin-xdoclet-definition -->
    * @generated     */
   public java.lang.String ping( java.lang.String param ) ;

}
