/*
 * Generated by XDoclet - Do not edit!
 */
package com.projst.ticket.service;

/**
 * Local home interface for TicketService.
 * @generated 
 * @wtp generated
 */
public interface TicketServiceLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TicketServiceLocal";
   public static final String JNDI_NAME="TicketServiceLocal";

   public com.projst.ticket.service.TicketServiceLocal create()
      throws javax.ejb.CreateException;

}
