/*
 * Generated by XDoclet - Do not edit!
 */
package com.projst.ticket.service;

/**
 * Home interface for TicketService.
 * @generated 
 * @wtp generated
 */
public interface TicketServiceHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TicketService";
   public static final String JNDI_NAME="TicketService";

   public com.projst.ticket.service.TicketService create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
