/*
 * Generated by XDoclet - Do not edit!
 */
package com.projst.ticket.entity;

/**
 * Data object for Ticket.
 * @generated 
 * @wtp generated
 */
public class TicketData
   extends java.lang.Object
   implements java.io.Serializable
{
   private java.lang.Integer id;
   private java.lang.String summary;
   private java.lang.String detail;
   private java.lang.String email;
   private java.sql.Timestamp submitted;
   private java.sql.Timestamp lastModified;

  /* begin value object */

  /* end value object */

   public TicketData()
   {
   }

   public TicketData( java.lang.Integer id,java.lang.String summary,java.lang.String detail,java.lang.String email,java.sql.Timestamp submitted,java.sql.Timestamp lastModified )
   {
      this.id = id;
      setSummary(summary);
      setDetail(detail);
      setEmail(email);
      setSubmitted(submitted);
      setLastModified(lastModified);
   }

   public TicketData( TicketData otherData )
   {
      this.id = otherData.id;
      setSummary(otherData.getSummary());
      setDetail(otherData.getDetail());
      setEmail(otherData.getEmail());
      setSubmitted(otherData.getSubmitted());
      setLastModified(otherData.getLastModified());

   }

   public java.lang.Integer getPrimaryKey() {
     return  getId();
   }

   public java.lang.Integer getId()
   {
      return this.id;
   }
   public void setId( java.lang.Integer id )
   {
      this.id = id;
   }

   public java.lang.String getSummary()
   {
      return this.summary;
   }
   public void setSummary( java.lang.String summary )
   {
      this.summary = summary;
   }

   public java.lang.String getDetail()
   {
      return this.detail;
   }
   public void setDetail( java.lang.String detail )
   {
      this.detail = detail;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }
   public void setEmail( java.lang.String email )
   {
      this.email = email;
   }

   public java.sql.Timestamp getSubmitted()
   {
      return this.submitted;
   }
   public void setSubmitted( java.sql.Timestamp submitted )
   {
      this.submitted = submitted;
   }

   public java.sql.Timestamp getLastModified()
   {
      return this.lastModified;
   }
   public void setLastModified( java.sql.Timestamp lastModified )
   {
      this.lastModified = lastModified;
   }

   public String toString()
   {
      StringBuffer str = new StringBuffer("{");

      str.append("id=" + getId() + " " + "summary=" + getSummary() + " " + "detail=" + getDetail() + " " + "email=" + getEmail() + " " + "submitted=" + getSubmitted() + " " + "lastModified=" + getLastModified());
      str.append('}');

      return(str.toString());
   }

   public boolean equals( Object pOther )
   {
      if( pOther instanceof TicketData )
      {
         TicketData lTest = (TicketData) pOther;
         boolean lEquals = true;

         if( this.id == null )
         {
            lEquals = lEquals && ( lTest.id == null );
         }
         else
         {
            lEquals = lEquals && this.id.equals( lTest.id );
         }
         if( this.summary == null )
         {
            lEquals = lEquals && ( lTest.summary == null );
         }
         else
         {
            lEquals = lEquals && this.summary.equals( lTest.summary );
         }
         if( this.detail == null )
         {
            lEquals = lEquals && ( lTest.detail == null );
         }
         else
         {
            lEquals = lEquals && this.detail.equals( lTest.detail );
         }
         if( this.email == null )
         {
            lEquals = lEquals && ( lTest.email == null );
         }
         else
         {
            lEquals = lEquals && this.email.equals( lTest.email );
         }
         if( this.submitted == null )
         {
            lEquals = lEquals && ( lTest.submitted == null );
         }
         else
         {
            lEquals = lEquals && this.submitted.equals( lTest.submitted );
         }
         if( this.lastModified == null )
         {
            lEquals = lEquals && ( lTest.lastModified == null );
         }
         else
         {
            lEquals = lEquals && this.lastModified.equals( lTest.lastModified );
         }

         return lEquals;
      }
      else
      {
         return false;
      }
   }

   public int hashCode()
   {
      int result = 17;

      result = 37*result + ((this.id != null) ? this.id.hashCode() : 0);

      result = 37*result + ((this.summary != null) ? this.summary.hashCode() : 0);

      result = 37*result + ((this.detail != null) ? this.detail.hashCode() : 0);

      result = 37*result + ((this.email != null) ? this.email.hashCode() : 0);

      result = 37*result + ((this.submitted != null) ? this.submitted.hashCode() : 0);

      result = 37*result + ((this.lastModified != null) ? this.lastModified.hashCode() : 0);

      return result;
   }

}
