/*
 * Generated by XDoclet - Do not edit!
 */
package com.projst.ticket.entity;

/**
 * Local home interface for Ticket.
 * @generated 
 * @wtp generated
 */
public interface TicketLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TicketLocal";
   public static final String JNDI_NAME="TicketLocal";

   public com.projst.ticket.entity.TicketLocal create(java.lang.String summary)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public com.projst.ticket.entity.TicketLocal findByPrimaryKey(java.lang.Integer pk)
      throws javax.ejb.FinderException;

}
