/*
 * Generated by XDoclet - Do not edit!
 */
package com.projst.ticket.service;

/**
 * Message Driven layer for EmailTicket.
 * @generated 
 * @wtp generated
 */
public class EmailTicketMdb
   extends com.projst.ticket.service.EmailTicketBean
   implements javax.jms.MessageListener,javax.ejb.MessageDrivenBean
{
   public void setMessageDrivenContext(javax.ejb.MessageDrivenContext ctx) throws javax.ejb.EJBException
   {
      super.setMessageDrivenContext(ctx);
   }

   public void ejbRemove() 
   {
      super.ejbRemove();
   }

}
