/*
 * Generated by XDoclet - Do not edit!
 */
package com.projst.ticket.service;

/**
 * Session layer for TicketService.
 * @generated 
 * @wtp generated
 */
public class TicketServiceSession
   extends com.projst.ticket.service.TicketServiceBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

}
